version: 2

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:8.11.3

restore_cache: &restore_cache
  restore_cache:
    name: Restore cache
    key: yvm-{{ .Branch }}-{{ checksum "package-lock.json" }}

save_cache: &save_cache
  save_cache:
    name: Save cache
    key: yvm-{{ .Branch }}-{{ checksum "package-lock.json" }}
    paths:
      - .yvm/
      - node_modules/

set_path: &set_path
  run:
    name: 'Set PATH'
    command: 'echo export PATH=$(pwd):$PATH > setpath.sh && source setpath.sh'

jobs:
  test:
    <<: *docker_defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          command: 'curl https://raw.githubusercontent.com/tophatmonocle/yvm/curl-bash/scripts/install.sh | bash'
          environment:
            YVM_DIR: '.yvm'
            YVM_ALIAS_DIR: '.'
      - *set_path
      - run: make lint
      # CODECOV_TOKEN is set by CIRCLE_CI
      - run: make test-coverage
      - store_test_results:
          path: artifacts/reports/tests
      - *save_cache
  build_and_deploy:
    <<: *docker_defaults
    steps:
      - checkout
      - *restore_cache
      - run: make build_and_deploy

workflows:
  version: 2
  test_and_deploy_master:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
